name: CI

on: [push, pull_request]

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-versions: [ '5.6', '7.4', '8.2' ]

        steps:
            - name: Code Checkout
              uses: actions/checkout@v3
              run: echo "The ${{ github.repository }} repository has been cloned to the runner."
            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                 php-version: ${{ matrix.php-versions }}
            - name: Composer
              uses: php-actions/composer@v6
              run: echo "Composer dependencies have been installed"
            - name: PHPUnit
              run: vendor/bin/phpunit
